sources:
  - name: snowsource
    database: SNOWDBT
    schema: PUBLIC
    tables:
      - name: EMP
      - name: SALES
      - name: SCD_DBT

models:
  - name: "rahul"
    config:
      materialized: 'table'
  - name: 'rahul2'
    config:
      materialized: 'view'
